name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  gnu-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        dotnet: [9.0.x]
        emacs_version:
          - 28.2
          - 29.4
          - snapshot
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh
      - name: Show dotnet sdks
        run: dotnet --list-sdks
      - name: Show dotnet version
        run: dotnet --info
      - name: Eldev archives
        run: |
          echo "Archives:"
          eldev archives
      - name: Eldev dependencies
        run: |
          echo "Dependencies:"
          eldev -v dependencies
      - name: Test
        run: |
          echo "Testing:"
          eldev -dtT test
          
  windows-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Show dotnet sdks
        run: dotnet --list-sdks
      - name: Show dotnet version
        run: dotnet --info
      - name: Set up Emacs on Windows
        uses: jcs090218/setup-emacs-windows@master
        with:
          version: 29.4
      - name: Install Eldev
        run: curl.exe -fsSL https://raw.github.com/doublep/eldev/master/webinstall/eldev.bat | cmd /Q
      - name: Eldev archives
        run: |
          echo "Archives:"
          ~/.local/bin/eldev.bat archives
      - name: Eldev dependencies
        run: |
          echo "Dependencies:"
          ~/.local/bin/eldev.bat dependencies
      - name: Test
        run: |
          echo "Testing:"
          ~/.local/bin/eldev.bat -p -dtT test
